const CACHE_VERSION = 'PACKIT_EQUIPMENT_SUMMARY_FIX_2026_05_24';
const CACHE_NAME = 'packit-equipment-summary-fix-2026-05-24';
const RUNTIME_CACHE = 'packit-runtime-equipment-summary-fix-2026-05-24';

const CORE_ASSETS = [
  './',
  './index.html',
  './manifest.json',
  './feg_svg_calibration.json',
  './src/README.md',
  './src/styles/main.css',
  './src/styles/tokens.css',
  './src/styles/reset.css',
  './src/styles/base.css',
  './src/styles/components/shell.css',
  './src/styles/components/brand-shell.css',
  './src/styles/components/layout.css',
  './src/styles/components/primitives.css',
  './src/styles/components/buttons-forms.css',
  './src/styles/components/tables-status.css',
  './src/styles/components/modals.css',
  './src/styles/modules/admin.css',
  './src/styles/modules/quote.css',
  './src/styles/modules/quote-equipment-layout.css',
  './src/styles/modules/quote-equipment-tighten.css',
  './src/styles/modules/quote-equipment-server-pass.css',
  './src/modules/index.js',
  './src/modules/FormatUtils.js',
  './src/modules/DomUtils.js',
  './src/modules/StageGridState.js',
  './src/modules/StageCalculator.js',
  './src/modules/AppSettings.js',
  './src/modules/SupabaseStorage.js',
  './src/modules/ProjectStorage.js',
  './src/modules/ClientsStorage.js',
  './src/modules/ClientsManager.js',
  './src/modules/PwaManager.js',
  './src/modules/ToastManager.js',
  './src/modules/BusyIndicator.js',
  './src/modules/TransportSettings.js',
  './src/modules/PriceWeightSettings.js',
  './src/modules/CalibrationManager.js',
  './src/modules/PdfGenerator.js',
  './src/modules/PackitAssetManifest.js',
  './src/modules/PackitShellBranding.js',
  './src/modules/TrussBlockConstructor.js',
  './src/modules/LoadChecker.js',
  './src/modules/RolePermissions.js',
  './src/modules/DemoAuthProvider.js',
  './src/modules/LocalAuthProvider.js',
  './src/modules/SupabaseAuthAdapter.js',
  './src/modules/SupabaseBackendPack.js',
  './src/modules/QuoteBackendSyncPack.js',
  './src/modules/ServerTestHarness.js',
  './src/modules/AuthProvider.js',
  './src/modules/AuthGuards.js',
  './src/modules/AuthShell.js',
  './src/modules/AdminShell.js',
  './src/modules/AdminControlCenter.js',
  './src/modules/DataQualityCenter.js',
  './src/modules/ReportsCenter.js',
  './src/modules/CommandCenter.js',
  './src/modules/CommunicationCenter.js',
  './src/modules/AccessOnboardingPanel.js',
  './src/modules/EquipmentDatabase.js',
  './src/modules/EquipmentServerBridge.js',
  './src/modules/EquipmentDatabaseUI.js',
  './src/modules/LedCalculator.js',
  './src/modules/LedCalculatorUI.js',
  './src/modules/V4StructureConfigurator.js',
  './src/modules/QuickIdealCatalog.js',
  './src/modules/V4StructureVisualConfigurator.js',
  './src/modules/V4SharedBomBridge.js',
  './src/modules/V4LedBomBridge.js',
  './src/modules/V4UnifiedBomExport.js',
  './src/modules/V4BomContract.js',
  './src/modules/SiteChecklist.js',
  './src/modules/ProjectCrewAssignments.js',
  './src/modules/UserDashboard.js',
  './src/modules/QuickTechnicalSheets.js',
  './src/modules/QuickCalculators.js',
  './src/modules/QuoteModel.js',
  './src/modules/QuoteDraftStorage.js',
  './src/modules/QuoteProjectStorage.js',
  './src/modules/QuoteEquipmentPicker.js',
  './src/modules/QuoteSectionBinder.js',
  './src/modules/QuoteSummaryBuilder.js',
  './src/modules/AvailabilityChecker.js',
  './src/modules/WarehousePickListBuilder.js',
  './src/modules/V4StabilizationSmokeMap.js',
  './src/modules/visual/StageVisualAdapter.js',
  './src/modules/visual/TrussVisualAdapter.js',
  './src/modules/visual/LedVisualAdapter.js',
  './src/modules/visual/AudioVisualAdapter.js',
  './src/modules/visual/LightVisualAdapter.js',
  './src/modules/visual/VisualModelBuilder.js',
  './src/modules/visual/ProjectRenderer2D.js',
  './src/modules/visual/ProjectRendererIso.js',
  './src/modules/visual/VisualExport.js',
  './src/modules/visual/VisualPreviewPanel.js',
  './src/modules/QuickPdfExport.js',
  './src/modules/SupplierDirectory.js',
  './src/modules/SubrentorsDirectoryUI.js',
  './src/modules/SubrentPlanner.js',
  './src/modules/ReservationPlanner.js',
  './src/modules/StockMovementPlanner.js',
  './src/modules/WarehouseWorkflow.js',
  './src/modules/WarehouseOperationsHub.js',
  './src/modules/PdfTemplateEngine.js',
  './src/modules/DocumentCenter.js',
  './src/modules/WorkspaceSettings.js',
  './src/modules/SettingsPanel.js',
  './src/modules/CalendarIntegration.js',
  './src/modules/QuoteDocumentBuilder.js',
  './src/modules/QuoteItemBuilder.js',
  './src/modules/V4QuoteDraftBomSink.js',
  './src/modules/V4QuoteDraftHydrator.js',
  './src/modules/V4BomInspector.js',
  './src/modules/BackendSyncAdapter.js',
  './src/modules/SupabaseSyncConsole.js',
  './src/modules/BackendWriteDryRun.js',
  './src/modules/QuoteServerSyncQueue.js',
  './src/modules/EquipmentServerSyncQueue.js',
  './src/modules/ProjectAuditLog.js',
  './src/modules/ImportRestoreCenter.js',
  './src/modules/ClientProjectLinks.js',
  './src/modules/ProjectTimelineView.js',
  './src/modules/ProjectReadinessChecklist.js',
  './src/modules/QuoteProjectsUI.js',
  './src/modules/V4ClientsPanel.js',
  './src/modules/QuoteWizard.js',
  './src/modules/QuoteEquipmentUiController.js',
  './src/modules/QuoteEquipmentLiveStateFix.js',
  './src/modules/QuoteEquipmentReentryGuard.js',
  './src/modules/V4DesignSystem.js',
  './src/modules/V4AppShell.js'
];

self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(CORE_ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key !== CACHE_NAME && key !== RUNTIME_CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  event.respondWith(caches.match(request).then(cached => {
    if (cached) return cached;
    return fetch(request).then(response => {
      if (!response || response.status !== 200 || response.type === 'opaque') return response;
      const clone = response.clone();
      caches.open(RUNTIME_CACHE).then(cache => cache.put(request, clone));
      return response;
    }).catch(() => caches.match('./index.html'));
  }));
});
